In [169]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [170]:
used_cars_df = pd.read_csv(r'../modified_data/cleaned_used_cars_dataset.csv')
used_cars_df

,Brand,model,Year,Age,kmDriven,Transmission,Owner,FuelType,PostedDate,AdditionInfo,AskPrice,postedMonth,postedYear,engine_l,brand_model,engine_l_imputed,kmDriven/year
0,Honda,City,2001,23,98000.0,Manual,second,Petrol,Nov-24,"Honda City v teck in mint condition, valid gen...",195000.0,11,2024,1.5,"Honda,City",1,4260.869565
1,Toyota,Innova,2009,15,190000.0,Manual,second,Diesel,Jul-24,"Toyota Innova 2.5 G (Diesel) 7 Seater, 2009, D...",375000.0,7,2024,2.5,"Toyota,Innova",0,12666.666667
2,Volkswagen,Vento,2010,14,77246.0,Manual,first,Diesel,Nov-24,"Volkswagen Vento 2010-2013 Diesel Breeze, 2010...",184999.0,11,2024,1.5,"Volkswagen,Vento",1,5517.571429
3,Maruti Suzuki,Swift,2017,7,83500.0,Manual,second,Diesel,Nov-24,Maruti Suzuki Swift 2017 Diesel Good Condition,565000.0,11,2024,1.2,"Maruti Suzuki,Swift",1,11928.571429
4,Maruti Suzuki,Baleno,2019,5,45000.0,Automatic,first,Petrol,Nov-24,"Maruti Suzuki Baleno Alpha CVT, 2019, Petrol",685000.0,11,2024,1.2,"Maruti Suzuki,Baleno",1,9000.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13890,Maruti Suzuki,Wagon R,2022,2,31000.0,Manual,first,hybrid,Nov-24,"Maruti Suzuki Wagon R LXI CNG Optional, 2022, ...",575000.0,11,2024,1.0,"Maruti Suzuki,Wagon R",1,15500.000000
13891,BMW,X1,2017,7,45000.0,Automatic,second,Diesel,Dec-24,"BMW X1 2.0 SDRIVE 20D, 2017, Diesel",1345000.0,12,2024,2.0,"BMW,X1",0,6428.571429
13892,Maruti Suzuki,New-gen Swift,2011,13,60000.0,Automatic,second,Diesel,Nov-24,Bahut badhiya new condition,160000.0,11,2024,1.2,"Maruti Suzuki,New-gen Swift",1,4615.384615
13893,Tata,Zest,2019,5,62000.0,Manual,second,hybrid,Nov-24,"Tata Zest Revotron 1.2T XE, 2019, CNG & Hybrids",380000.0,11,2024,1.2,"Tata,Zest",0,12400.000000
13894,Maruti Suzuki,Celerio,2019,5,18000.0,Manual,second,hybrid,Dec-24,"Maruti Suzuki Celerio CNG VXI MT, 2019, CNG & ...",450000.0,12,2024,1.0,"Maruti Suzuki,Celerio",1,3600.000000

In [171]:
cols=['Brand', 'brand_model','Age', 'kmDriven', 'engine_l', 'engine_l_imputed','Transmission', 'Owner', 'FuelType', 'AskPrice']
choosen_df = used_cars_df[cols]
choosen_df

,Brand,brand_model,Age,kmDriven,engine_l,engine_l_imputed,Transmission,Owner,FuelType,AskPrice
0,Honda,"Honda,City",23,98000.0,1.5,1,Manual,second,Petrol,195000.0
1,Toyota,"Toyota,Innova",15,190000.0,2.5,0,Manual,second,Diesel,375000.0
2,Volkswagen,"Volkswagen,Vento",14,77246.0,1.5,1,Manual,first,Diesel,184999.0
3,Maruti Suzuki,"Maruti Suzuki,Swift",7,83500.0,1.2,1,Manual,second,Diesel,565000.0
4,Maruti Suzuki,"Maruti Suzuki,Baleno",5,45000.0,1.2,1,Automatic,first,Petrol,685000.0
...,...,...,...,...,...,...,...,...,...,...
13890,Maruti Suzuki,"Maruti Suzuki,Wagon R",2,31000.0,1.0,1,Manual,first,hybrid,575000.0
13891,BMW,"BMW,X1",7,45000.0,2.0,0,Automatic,second,Diesel,1345000.0
13892,Maruti Suzuki,"Maruti Suzuki,New-gen Swift",13,60000.0,1.2,1,Automatic,second,Diesel,160000.0
13893,Tata,"Tata,Zest",5,62000.0,1.2,0,Manual,second,hybrid,380000.0
13894,Maruti Suzuki,"Maruti Suzuki,Celerio",5,18000.0,1.0,1,Manual,second,hybrid,450000.0

In [172]:
choosen_df.drop_duplicates(inplace=True)
choosen_df

,Brand,brand_model,Age,kmDriven,engine_l,engine_l_imputed,Transmission,Owner,FuelType,AskPrice
0,Honda,"Honda,City",23,98000.0,1.5,1,Manual,second,Petrol,195000.0
1,Toyota,"Toyota,Innova",15,190000.0,2.5,0,Manual,second,Diesel,375000.0
2,Volkswagen,"Volkswagen,Vento",14,77246.0,1.5,1,Manual,first,Diesel,184999.0
3,Maruti Suzuki,"Maruti Suzuki,Swift",7,83500.0,1.2,1,Manual,second,Diesel,565000.0
4,Maruti Suzuki,"Maruti Suzuki,Baleno",5,45000.0,1.2,1,Automatic,first,Petrol,685000.0
...,...,...,...,...,...,...,...,...,...,...
13890,Maruti Suzuki,"Maruti Suzuki,Wagon R",2,31000.0,1.0,1,Manual,first,hybrid,575000.0
13891,BMW,"BMW,X1",7,45000.0,2.0,0,Automatic,second,Diesel,1345000.0
13892,Maruti Suzuki,"Maruti Suzuki,New-gen Swift",13,60000.0,1.2,1,Automatic,second,Diesel,160000.0
13893,Tata,"Tata,Zest",5,62000.0,1.2,0,Manual,second,hybrid,380000.0
13894,Maruti Suzuki,"Maruti Suzuki,Celerio",5,18000.0,1.0,1,Manual,second,hybrid,450000.0

In [173]:
choosen_df.isna().mean()

Brand               0.0
brand_model         0.0
Age                 0.0
kmDriven            0.0
engine_l            0.0
engine_l_imputed    0.0
Transmission        0.0
Owner               0.0
FuelType            0.0
AskPrice            0.0
dtype: float64

In [174]:
feature_cols = ['Brand','brand_model','Age', 'kmDriven', 'engine_l', 'engine_l_imputed','Transmission', 'Owner', 'FuelType']

choosen_df.duplicated(subset=feature_cols)\
.sum()

np.int64(301)

In [175]:
choosen_df = (choosen_df.groupby(feature_cols, as_index=False)\
              .agg({'Brand':'first','engine_l':'first','engine_l_imputed':'first','AskPrice':'median'}))

In [176]:
choosen_df.duplicated(subset=feature_cols).sum()

np.int64(0)

In [177]:
choosen_df

,brand_model,Age,kmDriven,Transmission,Owner,FuelType,Brand,engine_l,engine_l_imputed,AskPrice
0,"Ambassador,Ambassador",1,54000.0,Manual,first,Petrol,Ambassador,1.5,1,421000.0
1,"Ambassador,Ambassador",9,18.0,Manual,second,Petrol,Ambassador,1.5,1,999599.0
2,"Ambassador,Ambassador",21,1.0,Manual,second,Petrol,Ambassador,1.5,1,155000.0
3,"Ashok Leyland,Stile",0,0.0,Automatic,first,Hybrid/CNG,Ashok Leyland,1.5,1,32000.0
4,"Aston Martin,Vanquish",8,25700.0,Automatic,first,Petrol,Aston Martin,6.0,0,26400000.0
...,...,...,...,...,...,...,...,...,...,...
13468,"Volvo,XC90",7,98000.0,Automatic,second,Diesel,Volvo,2.0,1,3000000.0
13469,"Volvo,XC90",8,102000.0,Automatic,first,Diesel,Volvo,2.0,0,3799000.0
13470,"Volvo,XC90",8,102000.0,Automatic,first,Diesel,Volvo,2.0,1,3749000.0
13471,"Volvo,XC90",9,125000.0,Automatic,second,Diesel,Volvo,2.0,1,1075000.0
13472,"Volvo,XC90",15,94000.0,Automatic,second,Diesel,Volvo,2.0,1,1250000.0

In [178]:
num_cols = choosen_df.select_dtypes(include=np.number).columns.tolist()
cat_cols = choosen_df.select_dtypes(include=str).columns.tolist()

cat_cols, num_cols

(['brand_model', 'Transmission', 'Owner', 'FuelType', 'Brand'],
 ['Age', 'kmDriven', 'engine_l', 'engine_l_imputed', 'AskPrice'])

In [179]:
choosen_df.describe()

,Age,kmDriven,engine_l,engine_l_imputed,AskPrice
count,13473.000000,13473.000000,13473.000000,13473.000000,1.347300e+04
mean,7.620797,71507.250204,1.514081,0.649595,9.845974e+05
std,4.137067,58870.940478,0.521589,0.477114,1.588896e+06
min,0.000000,0.000000,0.800000,0.000000,1.500000e+04
25%,5.000000,44000.000000,1.200000,0.000000,3.400000e+05
50%,7.000000,66000.000000,1.400000,1.000000,5.600000e+05
75%,10.000000,87000.000000,1.600000,1.000000,9.950000e+05
max,46.000000,980002.000000,6.650000,1.000000,4.250000e+07

In [180]:
display(choosen_df.loc[np.logical_and(choosen_df.kmDriven == 0, choosen_df.Age <= 1)])
display(choosen_df.loc[choosen_df.kmDriven == 0])

,brand_model,Age,kmDriven,Transmission,Owner,FuelType,Brand,engine_l,engine_l_imputed,AskPrice
3,"Ashok Leyland,Stile",0,0.0,Automatic,first,Hybrid/CNG,Ashok Leyland,1.5,1,32000.0
2415,"Hyundai,Aura",0,0.0,Automatic,first,hybrid,Hyundai,1.2,1,120000.0
2416,"Hyundai,Aura",0,0.0,Manual,first,hybrid,Hyundai,1.2,1,125000.0
4769,"Kia,Cerato",0,0.0,Automatic,first,Diesel,Kia,1.5,1,45000.0
5432,"Mahindra,Scorpio N",0,0.0,Manual,first,Diesel,Mahindra,2.2,1,1424700.0
5583,"Mahindra,Thar Roxx",0,0.0,Automatic,first,Diesel,Mahindra,2.0,1,21000.0
5591,"Mahindra,XUV 300",0,0.0,Manual,first,Petrol,Mahindra,1.2,0,749000.0
6003,"Maruti Suzuki,Alto 800",0,0.0,Automatic,first,hybrid,Maruti Suzuki,0.8,1,280000.0
6575,"Maruti Suzuki,Brezza",0,0.0,Automatic,first,hybrid,Maruti Suzuki,1.5,1,29000.0
7429,"Maruti Suzuki,Ertiga",0,0.0,Automatic,first,hybrid,Maruti Suzuki,1.5,0,350000.0
7430,"Maruti Suzuki,Ertiga",0,0.0,Manual,first,hybrid,Maruti Suzuki,1.5,0,320000.0
7864,"Maruti Suzuki,Fronx",0,0.0,Automatic,first,hybrid,Maruti Suzuki,1.2,1,972000.0
7870,"Maruti Suzuki,Fronx",1,0.0,Automatic,first,Petrol,Maruti Suzuki,1.2,1,1514981.0
7874,"Maruti Suzuki,Grand Vitara",0,0.0,Automatic,first,hybrid,Maruti Suzuki,1.5,1,3400000.0
11733,"Tata,Punch",0,0.0,Manual,first,hybrid,Tata,1.2,1,1059000.0
12860,"Toyota,Innova Hycross",0,0.0,Automatic,first,Hybrid/CNG,Toyota,2.0,0,3800000.0
12861,"Toyota,Innova Hycross",0,0.0,Automatic,first,Petrol,Toyota,2.0,0,1977000.0
12862,"Toyota,Innova Hycross",0,0.0,Automatic,first,hybrid,Toyota,2.0,0,3134000.0
12959,"Toyota,VELLFIRE",0,0.0,Automatic,first,hybrid,Toyota,2.5,1,200000.0

,brand_model,Age,kmDriven,Transmission,Owner,FuelType,Brand,engine_l,engine_l_imputed,AskPrice
3,"Ashok Leyland,Stile",0,0.0,Automatic,first,Hybrid/CNG,Ashok Leyland,1.5,1,32000.0
225,"Audi,Q3 Sportback",11,0.0,Automatic,second,hybrid,Audi,2.0,1,9500000.0
1059,"Ford,Endeavour",7,0.0,Manual,first,Diesel,Ford,3.2,1,2000000.0
1938,"Honda,City",13,0.0,Automatic,second,Hybrid/CNG,Honda,1.5,1,200000.0
1939,"Honda,City",13,0.0,Automatic,second,hybrid,Honda,1.5,1,200000.0
2415,"Hyundai,Aura",0,0.0,Automatic,first,hybrid,Hyundai,1.2,1,120000.0
2416,"Hyundai,Aura",0,0.0,Manual,first,hybrid,Hyundai,1.2,1,125000.0
3522,"Hyundai,Santro",21,0.0,Manual,second,Hybrid/CNG,Hyundai,1.4,1,52000.0
4769,"Kia,Cerato",0,0.0,Automatic,first,Diesel,Kia,1.5,1,45000.0
5261,"Mahindra,Jeep",30,0.0,Manual,second,Diesel,Mahindra,2.0,1,285000.0
5432,"Mahindra,Scorpio N",0,0.0,Manual,first,Diesel,Mahindra,2.2,1,1424700.0
5583,"Mahindra,Thar Roxx",0,0.0,Automatic,first,Diesel,Mahindra,2.0,1,21000.0
5591,"Mahindra,XUV 300",0,0.0,Manual,first,Petrol,Mahindra,1.2,0,749000.0
5848,"Maruti Suzuki,800",9,0.0,Automatic,second,hybrid,Maruti Suzuki,1.2,1,230000.0
6003,"Maruti Suzuki,Alto 800",0,0.0,Automatic,first,hybrid,Maruti Suzuki,0.8,1,280000.0
6178,"Maruti Suzuki,Alto 800",13,0.0,Manual,second,Petrol,Maruti Suzuki,0.8,1,140000.0
6575,"Maruti Suzuki,Brezza",0,0.0,Automatic,first,hybrid,Maruti Suzuki,1.5,1,29000.0
6971,"Maruti Suzuki,Ciaz",6,0.0,Manual,first,Petrol,Maruti Suzuki,1.5,1,500000.0
7313,"Maruti Suzuki,Eeco",6,0.0,Manual,second,Hybrid/CNG,Maruti Suzuki,1.2,1,350000.0
7429,"Maruti Suzuki,Ertiga",0,0.0,Automatic,first,hybrid,Maruti Suzuki,1.5,0,350000.0
7430,"Maruti Suzuki,Ertiga",0,0.0,Manual,first,hybrid,Maruti Suzuki,1.5,0,320000.0
7852,"Maruti Suzuki,Estilo",14,0.0,Automatic,second,Petrol,Maruti Suzuki,1.2,1,140000.0
7864,"Maruti Suzuki,Fronx",0,0.0,Automatic,first,hybrid,Maruti Suzuki,1.2,1,972000.0
7870,"Maruti Suzuki,Fronx",1,0.0,Automatic,first,Petrol,Maruti Suzuki,1.2,1,1514981.0
7874,"Maruti Suzuki,Grand Vitara",0,0.0,Automatic,first,hybrid,Maruti Suzuki,1.5,1,3400000.0
9271,"Maruti Suzuki,Wagon R",3,0.0,Manual,first,hybrid,Maruti Suzuki,1.2,0,589000.0
9412,"Maruti Suzuki,Wagon R",6,0.0,Automatic,first,Hybrid/CNG,Maruti Suzuki,1.0,1,449999.0
9485,"Maruti Suzuki,Wagon R",7,0.0,Manual,second,hybrid,Maruti Suzuki,1.0,1,395000.0
9777,"Maruti Suzuki,Wagon R",11,0.0,Automatic,second,hybrid,Maruti Suzuki,1.0,1,250000.0
11366,"Skoda,Superb",6,0.0,Automatic,first,Petrol,Skoda,1.8,0,1399999.0
11558,"Tata,Indigo Cs",15,0.0,Manual,second,Diesel,Tata,1.2,1,160000.0
11733,"Tata,Punch",0,0.0,Manual,first,hybrid,Tata,1.2,1,1059000.0
11774,"Tata,Safari",14,0.0,Manual,second,Diesel,Tata,2.0,1,290000.0
12576,"Toyota,Innova",12,0.0,Manual,second,Diesel,Toyota,2.5,0,595000.0
12860,"Toyota,Innova Hycross",0,0.0,Automatic,first,Hybrid/CNG,Toyota,2.0,0,3800000.0
12861,"Toyota,Innova Hycross",0,0.0,Automatic,first,Petrol,Toyota,2.0,0,1977000.0
12862,"Toyota,Innova Hycross",0,0.0,Automatic,first,hybrid,Toyota,2.0,0,3134000.0
12959,"Toyota,VELLFIRE",0,0.0,Automatic,first,hybrid,Toyota,2.5,1,200000.0

In [181]:
# XGBoost can work with NaNs so we will do the following 


choosen_df['engine_l'] = np.where(choosen_df['engine_l_imputed']==1, np.nan, choosen_df['engine_l'])

choosen_df

,brand_model,Age,kmDriven,Transmission,Owner,FuelType,Brand,engine_l,engine_l_imputed,AskPrice
0,"Ambassador,Ambassador",1,54000.0,Manual,first,Petrol,Ambassador,NaN,1,421000.0
1,"Ambassador,Ambassador",9,18.0,Manual,second,Petrol,Ambassador,NaN,1,999599.0
2,"Ambassador,Ambassador",21,1.0,Manual,second,Petrol,Ambassador,NaN,1,155000.0
3,"Ashok Leyland,Stile",0,0.0,Automatic,first,Hybrid/CNG,Ashok Leyland,NaN,1,32000.0
4,"Aston Martin,Vanquish",8,25700.0,Automatic,first,Petrol,Aston Martin,6.0,0,26400000.0
...,...,...,...,...,...,...,...,...,...,...
13468,"Volvo,XC90",7,98000.0,Automatic,second,Diesel,Volvo,NaN,1,3000000.0
13469,"Volvo,XC90",8,102000.0,Automatic,first,Diesel,Volvo,2.0,0,3799000.0
13470,"Volvo,XC90",8,102000.0,Automatic,first,Diesel,Volvo,NaN,1,3749000.0
13471,"Volvo,XC90",9,125000.0,Automatic,second,Diesel,Volvo,NaN,1,1075000.0
13472,"Volvo,XC90",15,94000.0,Automatic,second,Diesel,Volvo,NaN,1,1250000.0

In [182]:
# 1) near-zero km on an old car: treat as missing, not as real data
mask_low = (choosen_df.kmDriven < 1000) & (choosen_df.Age >= 5)
mask_high = np.where(choosen_df.kmDriven / choosen_df.Age.clip(lower=1) < 60000 , 0, 1)


choosen_df.loc[np.logical_or(mask_low, mask_high), 'kmDriven'] = np.nan

choosen_df

,brand_model,Age,kmDriven,Transmission,Owner,FuelType,Brand,engine_l,engine_l_imputed,AskPrice
0,"Ambassador,Ambassador",1,54000.0,Manual,first,Petrol,Ambassador,NaN,1,421000.0
1,"Ambassador,Ambassador",9,NaN,Manual,second,Petrol,Ambassador,NaN,1,999599.0
2,"Ambassador,Ambassador",21,NaN,Manual,second,Petrol,Ambassador,NaN,1,155000.0
3,"Ashok Leyland,Stile",0,0.0,Automatic,first,Hybrid/CNG,Ashok Leyland,NaN,1,32000.0
4,"Aston Martin,Vanquish",8,25700.0,Automatic,first,Petrol,Aston Martin,6.0,0,26400000.0
...,...,...,...,...,...,...,...,...,...,...
13468,"Volvo,XC90",7,98000.0,Automatic,second,Diesel,Volvo,NaN,1,3000000.0
13469,"Volvo,XC90",8,102000.0,Automatic,first,Diesel,Volvo,2.0,0,3799000.0
13470,"Volvo,XC90",8,102000.0,Automatic,first,Diesel,Volvo,NaN,1,3749000.0
13471,"Volvo,XC90",9,125000.0,Automatic,second,Diesel,Volvo,NaN,1,1075000.0
13472,"Volvo,XC90",15,94000.0,Automatic,second,Diesel,Volvo,NaN,1,1250000.0

In [183]:
choosen_df.isna().mean()*100

brand_model          0.000000
Age                  0.000000
kmDriven             1.632895
Transmission         0.000000
Owner                0.000000
FuelType             0.000000
Brand                0.000000
engine_l            64.959549
engine_l_imputed     0.000000
AskPrice             0.000000
dtype: float64

In [184]:
print(choosen_df[choosen_df.kmDriven.isna()].brand_model.value_counts().head())
print(choosen_df[choosen_df.kmDriven.isna()].Age.describe())

brand_model
Maruti Suzuki,Wagon R        23
Maruti Suzuki,Ertiga         13
Maruti Suzuki,Swift Dzire    13
Maruti Suzuki,Eeco           11
Honda,City                    8
Name: count, dtype: int64
count    220.000000
mean       8.350000
std        4.944463
min        0.000000
25%        5.000000
50%        8.000000
75%       12.000000
max       30.000000
Name: Age, dtype: float64

In [185]:
bm_group = choosen_df.groupby('brand_model')
bm_group_median_price = bm_group['AskPrice'].transform('median')
bm_group_count = bm_group['AskPrice'].transform('size')

askprice_median_ratio = choosen_df.AskPrice / bm_group_median_price
unbiased_sample = (bm_group_count >= 20)

low_mask = (unbiased_sample) & (askprice_median_ratio < 0.15) & (choosen_df.Age <=10)
high_mask = (unbiased_sample) & (askprice_median_ratio > 5)

choosen_df.loc[high_mask, 'AskPrice'] = (bm_group_median_price * 5)[high_mask]
choosen_df = choosen_df[~low_mask].reset_index(drop=True)

In [186]:
choosen_df

,brand_model,Age,kmDriven,Transmission,Owner,FuelType,Brand,engine_l,engine_l_imputed,AskPrice
0,"Ambassador,Ambassador",1,54000.0,Manual,first,Petrol,Ambassador,NaN,1,421000.0
1,"Ambassador,Ambassador",9,NaN,Manual,second,Petrol,Ambassador,NaN,1,999599.0
2,"Ambassador,Ambassador",21,NaN,Manual,second,Petrol,Ambassador,NaN,1,155000.0
3,"Ashok Leyland,Stile",0,0.0,Automatic,first,Hybrid/CNG,Ashok Leyland,NaN,1,32000.0
4,"Aston Martin,Vanquish",8,25700.0,Automatic,first,Petrol,Aston Martin,6.0,0,26400000.0
...,...,...,...,...,...,...,...,...,...,...
13455,"Volvo,XC90",7,98000.0,Automatic,second,Diesel,Volvo,NaN,1,3000000.0
13456,"Volvo,XC90",8,102000.0,Automatic,first,Diesel,Volvo,2.0,0,3799000.0
13457,"Volvo,XC90",8,102000.0,Automatic,first,Diesel,Volvo,NaN,1,3749000.0
13458,"Volvo,XC90",9,125000.0,Automatic,second,Diesel,Volvo,NaN,1,1075000.0
13459,"Volvo,XC90",15,94000.0,Automatic,second,Diesel,Volvo,NaN,1,1250000.0

In [187]:
choosen_df.FuelType.value_counts()

FuelType
Petrol        5204
Diesel        4660
hybrid        1842
Hybrid/CNG    1754
Name: count, dtype: int64

In [188]:
choosen_df.FuelType

0            Petrol
1            Petrol
2            Petrol
3        Hybrid/CNG
4            Petrol
            ...
13455        Diesel
13456        Diesel
13457        Diesel
13458        Diesel
13459        Diesel
Name: FuelType, Length: 13460, dtype: str

In [189]:
choosen_df['FuelType'] = choosen_df.FuelType.map({'hybrid':'CNG', 'Hybrid/CNG':'CNG', 'Petrol':'Petrol', 'Diesel':'Diesel'})

In [190]:
choosen_df

,brand_model,Age,kmDriven,Transmission,Owner,FuelType,Brand,engine_l,engine_l_imputed,AskPrice
0,"Ambassador,Ambassador",1,54000.0,Manual,first,Petrol,Ambassador,NaN,1,421000.0
1,"Ambassador,Ambassador",9,NaN,Manual,second,Petrol,Ambassador,NaN,1,999599.0
2,"Ambassador,Ambassador",21,NaN,Manual,second,Petrol,Ambassador,NaN,1,155000.0
3,"Ashok Leyland,Stile",0,0.0,Automatic,first,CNG,Ashok Leyland,NaN,1,32000.0
4,"Aston Martin,Vanquish",8,25700.0,Automatic,first,Petrol,Aston Martin,6.0,0,26400000.0
...,...,...,...,...,...,...,...,...,...,...
13455,"Volvo,XC90",7,98000.0,Automatic,second,Diesel,Volvo,NaN,1,3000000.0
13456,"Volvo,XC90",8,102000.0,Automatic,first,Diesel,Volvo,2.0,0,3799000.0
13457,"Volvo,XC90",8,102000.0,Automatic,first,Diesel,Volvo,NaN,1,3749000.0
13458,"Volvo,XC90",9,125000.0,Automatic,second,Diesel,Volvo,NaN,1,1075000.0
13459,"Volvo,XC90",15,94000.0,Automatic,second,Diesel,Volvo,NaN,1,1250000.0

In [191]:
choosen_df.columns

Index(['brand_model', 'Age', 'kmDriven', 'Transmission', 'Owner', 'FuelType',
       'Brand', 'engine_l', 'engine_l_imputed', 'AskPrice'],
      dtype='str')

In [192]:
from sklearn.model_selection import train_test_split, cross_val_score, KFold

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import OneHotEncoder, TargetEncoder
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from xgboost import XGBRegressor

In [193]:
y = np.log1p(choosen_df['AskPrice'])
X = choosen_df.drop(columns=['AskPrice', 'Brand', 'engine_l_imputed'], errors='ignore')

num_cols = ['Age', 'kmDriven', 'engine_l']          
bin_cols = ['Transmission', 'Owner']
cat_cols = ['FuelType']
te_cols  = ['brand_model']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [194]:
pre = ColumnTransformer([
    ('te',  TargetEncoder(cv=5, random_state=0), te_cols),
    ('bin', OneHotEncoder(drop='if_binary', sparse_output=False), bin_cols),
    ('ohe', OneHotEncoder(handle_unknown='ignore', sparse_output=False), cat_cols),
    ('num', 'passthrough', num_cols),
])

model = Pipeline([
    ('pre', pre),
    ('xgb', XGBRegressor(n_estimators=600, learning_rate=0.05, max_depth=6,
                         subsample=0.8, colsample_bytree=0.8, random_state=0, n_jobs=-1)),
])

In [195]:
cv_rmse = -cross_val_score(model, X_train, y_train, scoring='neg_root_mean_squared_error',
                           cv=KFold(5, shuffle=True, random_state=0))
print(f"CV RMSE (log scale): {cv_rmse.mean():.4f} ± {cv_rmse.std():.4f}")

model.fit(X_train, y_train)
pred = model.predict(X_test)

c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(

CV RMSE (log scale): 0.3075 ± 0.0115

c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(

In [196]:
print(f"Test RMSE (log): {np.sqrt(mean_squared_error(y_test, pred)):.4f}")
print(f"Test R2        : {r2_score(y_test, pred):.4f}")
print(f"Test MAE (INR) : {mean_absolute_error(np.expm1(y_test), np.expm1(pred)):,.0f}")
print(f"Median % error : {np.median(np.abs(np.expm1(pred) / np.expm1(y_test) - 1)) * 100:.1f}%")

Test RMSE (log): 0.3260
Test R2        : 0.8775
Test MAE (INR) : 239,036
Median % error : 14.3%

In [197]:
import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator, RegressorMixin

In [198]:
class GroupMedianRegressor(BaseEstimator, RegressorMixin):
    """Predicts the median target of each group (e.g. brand_model).
    Unseen groups fall back to the global training median."""

    def __init__(self, group_col='brand_model'):
        self.group_col = group_col

    def fit(self, X, y):
        y = pd.Series(np.asarray(y), index=X.index)
        self.group_medians_ = y.groupby(X[self.group_col]).median()
        self.global_median_ = float(y.median())
        return self

    def predict(self, X):
        return (X[self.group_col].map(self.group_medians_)
                                  .fillna(self.global_median_)
                                  .to_numpy())

In [199]:
base = GroupMedianRegressor().fit(X_train, y_train)
base_pred = base.predict(X_test)

rmse = lambda a, b: np.sqrt(mean_squared_error(a, b))

print(f"GroupMedian  RMSE (log): {rmse(y_test, base_pred):.4f} | R2: {r2_score(y_test, base_pred):.4f} | "
      f"median % err: {np.median(np.abs(np.expm1(base_pred) / np.expm1(y_test) - 1)) * 100:.1f}%")
print(f"XGBoost      RMSE (log): {rmse(y_test, pred):.4f} | R2: {r2_score(y_test, pred):.4f} | "
      f"median % err: {np.median(np.abs(np.expm1(pred) / np.expm1(y_test) - 1)) * 100:.1f}%")


cv = KFold(5, shuffle=True, random_state=0)
base_cv = -cross_val_score(GroupMedianRegressor(), X_train, y_train,
                           scoring='neg_root_mean_squared_error', cv=cv)
print(f"GroupMedian CV RMSE: {base_cv.mean():.4f} ± {base_cv.std():.4f}")

GroupMedian  RMSE (log): 0.4767 | R2: 0.7381 | median % err: 22.5%
XGBoost      RMSE (log): 0.3260 | R2: 0.8775 | median % err: 14.3%
GroupMedian CV RMSE: 0.4624 ± 0.0119

In [200]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint, uniform

param_dist = {
    'xgb__n_estimators':     randint(300, 1500),
    'xgb__learning_rate':    uniform(0.01, 0.09),    # 0.01 - 0.10
    'xgb__max_depth':        randint(3, 10),
    'xgb__min_child_weight': randint(1, 12),
    'xgb__subsample':        uniform(0.6, 0.4),      # 0.6 - 1.0
    'xgb__colsample_bytree': uniform(0.5, 0.5),      # 0.5 - 1.0
    'xgb__gamma':            uniform(0, 0.5),
    'xgb__reg_alpha':        uniform(0, 2),
    'xgb__reg_lambda':       uniform(0.5, 5),
}

search = RandomizedSearchCV(
    model,                                           # your exact pipeline
    param_distributions=param_dist,
    n_iter=40,
    cv=KFold(5, shuffle=True, random_state=0),       # same CV as your baseline
    scoring='neg_root_mean_squared_error',           # same metric as your baseline
    random_state=0,
    n_jobs=1,                                        # XGBoost already uses all cores
    verbose=1,
)
search.fit(X_train, y_train)

print(f"baseline CV RMSE : {cv_rmse.mean():.4f} ± {cv_rmse.std():.4f}")
print(f"tuned    CV RMSE : {-search.best_score_:.4f}")
print({k.replace('xgb__', ''): (round(v, 4) if isinstance(v, float) else v)
       for k, v in search.best_params_.items()})

# one look at the test set, same metrics as before
tuned = search.best_estimator_
pred_t = tuned.predict(X_test)
print(f"\nTest RMSE (log): {np.sqrt(mean_squared_error(y_test, pred_t)):.4f}")
print(f"Test R2        : {r2_score(y_test, pred_t):.4f}")
print(f"Test MAE (INR) : {mean_absolute_error(np.expm1(y_test), np.expm1(pred_t)):,.0f}")
print(f"Median % error : {np.median(np.abs(np.expm1(pred_t) / np.expm1(y_test) - 1)) * 100:.1f}%")

Fitting 5 folds for each of 40 candidates, totalling 200 fits

c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(
c:\Users\ADMIN\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\preprocessing\_target_encoder.py:342: FutureWarning: `TargetEncoder.shuffle` and `TargetEncoder.random_state` are deprecated in version 1.9 and will be removed in version 1.11. Pass a cross-validation generator as `cv` argument to specify the shuffling behaviour instead.
  warnings.warn(

baseline CV RMSE : 0.3075 ± 0.0115
tuned    CV RMSE : 0.3035
{'colsample_bytree': np.float64(0.9591), 'gamma': np.float64(0.1084), 'learning_rate': np.float64(0.0609), 'max_depth': 7, 'min_child_weight': 2, 'n_estimators': 862, 'reg_alpha': np.float64(1.0465), 'reg_lambda': np.float64(0.9697), 'subsample': np.float64(0.8304)}

Test RMSE (log): 0.3228
Test R2        : 0.8799
Test MAE (INR) : 238,216
Median % error : 14.3%

In [201]:
import joblib
from pathlib import Path

path = Path("../final_tuned_model")
path.mkdir(parents=True, exist_ok=True)

# (optional) silence the TargetEncoder warning without changing behavior
tuned = search.best_estimator_
tuned.set_params(pre__te=TargetEncoder(cv=KFold(5, shuffle=True, random_state=0)))

# retrain on all data and save
feature_cols = te_cols + bin_cols + cat_cols + num_cols
final_model = tuned.fit(X[feature_cols], y)
joblib.dump({'model': final_model, 'features': feature_cols}, path/'used_car_price_model.joblib')

# helper for new cars
def predict_price(df_new):
    return np.expm1(final_model.predict(df_new[feature_cols]))

# quick sanity check on one example
example = pd.DataFrame([{
    'brand_model': 'Maruti Suzuki,Swift', 'Age': 6, 'kmDriven': 60000, 'engine_l': 1.2,
    'Transmission': 'Manual', 'Owner': 'first', 'FuelType': 'Petrol'}])
print(f"{predict_price(example)[0]:,.0f}")

541,870